name: "Docker Lint"

on:
  pull_request:
  workflow_dispatch:

jobs:
  navigation-test:
    uses: catie-aq/generic_workflows/.github/workflows/docker-test.yaml@main
    with:
      dockerfile: Dockerfile
      ignore: DL3008, DL3015, SC1091
