name: "Docker Lint"

on:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  check-dockerfile:
    uses: catie-aq/generic_workflows/.github/workflows/docker-test.yaml@main
    with:
      dockerfile: Dockerfile
      ignore: DL3008, DL3015, SC1091, SC2046
