name: Publish to GHCR CI and Dev images

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  publish-ci:
    uses: catie-aq/generic_workflows/.github/workflows/docker-ghcr.yml@main
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
    with:
      target: ci
  publish-dev:
    uses: catie-aq/generic_workflows/.github/workflows/docker-ghcr.yml@main
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
    with:
      target: dev
