name: Publish to GHCR

on:
  push:
  workflow_dispatch:

jobs:
    publish:
        uses: catie-aq/generic_workflows/.github/workflows/docker-ghcr.yml@main
        secrets:
            PAT: ${{ secrets.GITHUB_TOKEN }}