name: Publish to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  publish:
    uses: catie-aq/generic_workflows/.github/workflows/docker-ghcr.yml@main
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
  publish-workspace:
    uses: catie-aq/generic_workflows/.github/workflows/docker-ghcr.yml@main
    secrets:
      PAT: ${{ secrets.GITHUB_TOKEN }}
    with:
      target: workspace
