name: Update Dockerfile and Tag

on:
  push:

jobs:
  update-dockerfile:
    runs-on: sonu-github-arc
    container:
      image: ubuntu:latest

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl jq git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: workdir

      - name: Get latest tag from zephyrproject-rtos/docker-image
        id: get_latest_zephyr_tag
        run: |
          latest_zephyr_tag=$(curl -s https://api.github.com/repos/zephyrproject-rtos/docker-image/tags | jq -r '.[0].name')
          echo "::set-output name=zephyr_tag::$latest_zephyr_tag"

      - name: Get latest tag from current repository
        id: get_latest_current_tag
        run: |
          cd workdir
          latest_current_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=current_tag::$latest_current_tag"

      - name: Update Dockerfile, commit, push changes, and create new tag if necessary
        if: steps.get_latest_zephyr_tag.outputs.zephyr_tag != steps.get_latest_current_tag.outputs.current_tag
        run: |
          cd workdir
          latest_zephyr_tag=${{ steps.get_latest_zephyr_tag.outputs.zephyr_tag }}
          sed -i "s|^FROM zephyrprojectrtos/ci:.*|FROM zephyrprojectrtos/ci:${latest_zephyr_tag}|" Dockerfile
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Dockerfile
          git commit -m "Update Dockerfile to use zephyrprojectrtos/ci:${latest_zephyr_tag}"
          git push origin main
          git tag $latest_zephyr_tag
          git push origin $latest_zephyr_tag
