name: Update Dockerfile and Tag

on:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  update-dockerfile:
    runs-on: sonu-github-arc
    container:
      image: ubuntu:latest

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl jq git

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: workdir

      - name: Get latest tag from zephyrproject-rtos/docker-image
        id: get_latest_zephyr_tag
        run: |
          latest_zephyr_tag=$(curl -s https://api.github.com/repos/zephyrproject-rtos/docker-image/tags | jq -r '.[0].name')
          echo "::set-output name=zephyr_tag::$latest_zephyr_tag"

      - name: Get Previous tag
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          workingDirectory: workdir

      - name: Update Dockerfile, commit, push changes, and create new tag if necessary
        if: steps.get_latest_zephyr_tag.outputs.zephyr_tag != steps.previous_tag.outputs.tag
        run: |
          cd workdir
          latest_zephyr_tag=${{ steps.get_latest_zephyr_tag.outputs.zephyr_tag }}
          sed -i "s|^FROM zephyrprojectrtos/ci:.*|FROM zephyrprojectrtos/ci:${latest_zephyr_tag}|" Dockerfile

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: workdir
          branch: update-dockerfile-${{ steps.get_latest_zephyr_tag.outputs.zephyr_tag }}
          title: "Update Dockerfile to use zephyrprojectrtos/ci:${{ steps.get_latest_zephyr_tag.outputs.zephyr_tag }}"
          commit-message: "Update Dockerfile to use zephyrprojectrtos/ci:${{ steps.get_latest_zephyr_tag.outputs.zephyr_tag }}"
          author: GitHub <noreply@github.com>
          labels: dependencies
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
          reviewers: clementlgl
